<?php

namespace Database\Seeders;

use App\Models\Component;
use Illuminate\Database\Seeder;

class ComponentSeeder extends Seeder
{
    public function run(): void
    {
        $components = [
            // IoT Components
            [
                'name'        => 'Arduino Uno R3',
                'code'        => 'KMP-001',
                'category'    => 'IoT',
                'brand'       => 'Arduino',
                'model'       => 'Uno R3',
                'quantity'    => 25,
                'status'      => 'Tersedia',
                'description' => 'Microcontroller board berbasis ATmega328P',
            ],
            [
                'name'        => 'NodeMCU ESP8266',
                'code'        => 'KMP-002',
                'category'    => 'IoT',
                'brand'       => 'WeMos',
                'model'       => 'NodeMCU V3',
                'quantity'    => 20,
                'status'      => 'Tersedia',
                'description' => 'WiFi microcontroller dengan ESP8266',
            ],
            [
                'name'        => 'ESP32 DevKit',
                'code'        => 'KMP-003',
                'category'    => 'IoT',
                'brand'       => 'Espressif',
                'model'       => 'ESP32-WROOM-32',
                'quantity'    => 15,
                'status'      => 'Tersedia',
                'description' => 'WiFi + Bluetooth microcontroller',
            ],
            [
                'name'        => 'Raspberry Pi 4 Model B',
                'code'        => 'KMP-004',
                'category'    => 'IoT',
                'brand'       => 'Raspberry Pi',
                'model'       => '4B 4GB',
                'quantity'    => 10,
                'status'      => 'Digunakan',
                'description' => 'Single-board computer untuk proyek IoT',
            ],
            [
                'name'        => 'Sensor DHT22',
                'code'        => 'KMP-005',
                'category'    => 'IoT',
                'brand'       => 'Aosong',
                'model'       => 'DHT22/AM2302',
                'quantity'    => 30,
                'status'      => 'Tersedia',
                'description' => 'Sensor suhu dan kelembaban',
            ],
            [
                'name'        => 'Sensor Ultrasonik HC-SR04',
                'code'        => 'KMP-006',
                'category'    => 'IoT',
                'brand'       => 'Hyrotech',
                'model'       => 'HC-SR04',
                'quantity'    => 25,
                'status'      => 'Tersedia',
                'description' => 'Sensor jarak ultrasonik',
            ],
            [
                'name'        => 'Modul Relay 4 Channel',
                'code'        => 'KMP-007',
                'category'    => 'IoT',
                'brand'       => 'SainSmart',
                'model'       => 'Relay 4CH 5V',
                'quantity'    => 20,
                'status'      => 'Tersedia',
                'description' => 'Modul relay 4 channel untuk kontrol perangkat',
            ],
            [
                'name'        => 'LED Strip WS2812B',
                'code'        => 'KMP-008',
                'category'    => 'IoT',
                'brand'       => 'Generic',
                'model'       => 'WS2812B 1m',
                'quantity'    => 15,
                'status'      => 'Tersedia',
                'description' => 'LED addressable RGB 60 LED/meter',
            ],
            [
                'name'        => 'OLED Display 0.96"',
                'code'        => 'KMP-009',
                'category'    => 'IoT',
                'brand'       => 'SSD1306',
                'model'       => '0.96" I2C',
                'quantity'    => 20,
                'status'      => 'Tersedia',
                'description' => 'Display OLED 128x64 I2C',
            ],
            [
                'name'        => 'Breadboard 830 Point',
                'code'        => 'KMP-010',
                'category'    => 'IoT',
                'brand'       => 'Generic',
                'model'       => 'SYB-120',
                'quantity'    => 40,
                'status'      => 'Tersedia',
                'description' => 'Breadboard untuk prototyping',
            ],

            // Jaringan Components
            [
                'name'        => 'Cisco Router ISR 1100',
                'code'        => 'KMP-101',
                'category'    => 'Jaringan',
                'brand'       => 'Cisco',
                'model'       => 'ISR 1111',
                'quantity'    => 5,
                'status'      => 'Tersedia',
                'description' => 'Router enterprise untuk lab jaringan',
            ],
            [
                'name'        => 'Cisco Switch 2960',
                'code'        => 'KMP-102',
                'category'    => 'Jaringan',
                'brand'       => 'Cisco',
                'model'       => 'WS-C2960-24TT-L',
                'quantity'    => 8,
                'status'      => 'Tersedia',
                'description' => 'Managed switch 24 port',
            ],
            [
                'name'        => 'MikroTik RouterBOARD',
                'code'        => 'KMP-103',
                'category'    => 'Jaringan',
                'brand'       => 'MikroTik',
                'model'       => 'RB750Gr3',
                'quantity'    => 10,
                'status'      => 'Tersedia',
                'description' => 'Routerboard untuk konfigurasi jaringan',
            ],
            [
                'name'        => 'TP-Link Access Point',
                'code'        => 'KMP-104',
                'category'    => 'Jaringan',
                'brand'       => 'TP-Link',
                'model'       => 'EAP245',
                'quantity'    => 8,
                'status'      => 'Tersedia',
                'description' => 'Wireless access point dual-band',
            ],
            [
                'name'        => 'Kabel UTP Cat6 (Roll)',
                'code'        => 'KMP-105',
                'category'    => 'Jaringan',
                'brand'       => 'Belden',
                'model'       => 'Cat6 UTP',
                'quantity'    => 50,
                'status'      => 'Tersedia',
                'description' => 'Kabel UTP Cat6 per meter',
            ],
            [
                'name'        => 'Crimping Tool RJ45',
                'code'        => 'KMP-106',
                'category'    => 'Jaringan',
                'brand'       => 'Generic',
                'model'       => 'RJ45 Crimper',
                'quantity'    => 15,
                'status'      => 'Tersedia',
                'description' => 'Tang crimping untuk konektor RJ45',
            ],
            [
                'name'        => 'Connector RJ45 Cat6',
                'code'        => 'KMP-107',
                'category'    => 'Jaringan',
                'brand'       => 'Generic',
                'model'       => 'RJ45 Cat6',
                'quantity'    => 200,
                'status'      => 'Tersedia',
                'description' => 'Konektor RJ45 Cat6 (box 100 pcs)',
            ],
            [
                'name'        => 'Network Cable Tester',
                'code'        => 'KMP-108',
                'category'    => 'Jaringan',
                'brand'       => 'Generic',
                'model'       => 'NS-468',
                'quantity'    => 10,
                'status'      => 'Tersedia',
                'description' => 'Alat tes kabel jaringan',
            ],
            [
                'name'        => 'Patch Panel 24 Port',
                'code'        => 'KMP-109',
                'category'    => 'Jaringan',
                'brand'       => 'Generic',
                'model'       => 'Cat6 24P',
                'quantity'    => 5,
                'status'      => 'Tersedia',
                'description' => 'Patch panel 24 port Cat6',
            ],
            [
                'name'        => 'Fiber Optic Media Converter',
                'code'        => 'KMP-110',
                'category'    => 'Jaringan',
                'brand'       => 'TP-Link',
                'model'       => 'MC220L',
                'quantity'    => 6,
                'status'      => 'Maintenance',
                'description' => 'Media converter fiber to ethernet',
            ],
        ];

        foreach ($components as $component) {
            Component::create($component);
        }
    }
}
